In [1]:
%pip install pandas

Requirement already satisfied: pandas in C:\Users\HP\AppData\Roaming\Python\Python313\site-packages (3.0.0)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\HP\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\HP\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\HP\AppData\Roaming\Python\Python313\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\HP\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd 
pd.__version__

'3.0.0'

In [4]:
di = {
    "ID":[101,102,103,104,105,106,107,108,109,110],
    "Name":["Rohan","mohit","yash","keshav","karan","rahul","aryan","arjun","aditya","chandan"],
    "Age":[27,29,37,34,39,24,26,31,28,33,],
    "Dept":["IT","Sales","HR","IT","Sales","Operations","IT","Sales","HR","Operations"],
    "Salary":[72000,43000,32000,55000,49000,79000,124000,91000,67000,70000]
}

In [5]:
pd.DataFrame(di)

    ID     Name  Age        Dept  Salary
0  101    Rohan   27          IT   72000
1  102    mohit   29       Sales   43000
2  103     yash   37          HR   32000
3  104   keshav   34          IT   55000
4  105    karan   39       Sales   49000
5  106    rahul   24  Operations   79000
6  107    aryan   26          IT  124000
7  108    arjun   31       Sales   91000
8  109   aditya   28          HR   67000
9  110  chandan   33  Operations   70000

In [6]:
df = pd.DataFrame(di)

In [7]:
df

    ID     Name  Age        Dept  Salary
0  101    Rohan   27          IT   72000
1  102    mohit   29       Sales   43000
2  103     yash   37          HR   32000
3  104   keshav   34          IT   55000
4  105    karan   39       Sales   49000
5  106    rahul   24  Operations   79000
6  107    aryan   26          IT  124000
7  108    arjun   31       Sales   91000
8  109   aditya   28          HR   67000
9  110  chandan   33  Operations   70000

In [8]:
print(type(df))

<class 'pandas.DataFrame'>

In [9]:
type(df["Name"]).dtype

In [10]:
df["Salary"]

0     72000
1     43000
2     32000
3     55000
4     49000
5     79000
6    124000
7     91000
8     67000
9     70000
Name: Salary, dtype: int64

In [11]:
df["Age"].dtype

dtype('int64')

In [12]:
type(df["Age"]).dtype

In [13]:
type(df["Salary"]).dtype

In [14]:
df["Salary"].dtype

dtype('int64')

In [15]:
# iloc Method ------ df .iloc(row_index , col_index)
df.iloc[6,1]

'aryan'

In [16]:
df.iloc[3,4]

np.int64(55000)

In [17]:
# loc Method ---- df.loc(row_index , col_name)
df.iloc[6, 1]

'aryan'

In [18]:
#iloc slicing
df.iloc[4 , :]

ID          105
Name      karan
Age          39
Dept      Sales
Salary    49000
Name: 4, dtype: object

In [19]:
di = {
    "ID":[101,102,103,104,105,106,107,108,109,110],
    "Name":["Rohan","mohit","yash","keshav","karan","rahul","aryan","arjun","aditya","chandan"],
    "Age":[27,29,37,34,39,24,26,31,28,33,],
    "Dept":["IT","Sales","HR","IT","Sales","Operations","IT","Sales","HR","Operations"],
    "Salary":[72000,43000,32000,55000,49000,79000,124000,91000,67000,70000]
}

In [20]:
df = pd.DataFrame(di)
df

    ID     Name  Age        Dept  Salary
0  101    Rohan   27          IT   72000
1  102    mohit   29       Sales   43000
2  103     yash   37          HR   32000
3  104   keshav   34          IT   55000
4  105    karan   39       Sales   49000
5  106    rahul   24  Operations   79000
6  107    aryan   26          IT  124000
7  108    arjun   31       Sales   91000
8  109   aditya   28          HR   67000
9  110  chandan   33  Operations   70000

In [21]:
# Head Method ---df.Head()
df.head(2)

    ID   Name  Age   Dept  Salary
0  101  Rohan   27     IT   72000
1  102  mohit   29  Sales   43000

In [22]:
# Tail Method ---df.tail()
df.tail(2)

    ID     Name  Age        Dept  Salary
8  109   aditya   28          HR   67000
9  110  chandan   33  Operations   70000

In [23]:
# D3scribe Method -- df.Describe()
df.describe()

              ID        Age         Salary
count   10.00000  10.000000      10.000000
mean   105.50000  30.800000   68200.000000
std      3.02765   4.894441   26368.331174
min    101.00000  24.000000   32000.000000
25%    103.25000  27.250000   50500.000000
50%    105.50000  30.000000   68500.000000
75%    107.75000  33.750000   77250.000000
max    110.00000  39.000000  124000.000000

In [24]:
# astype method --- df{col},astype(type)
df["ID"] = df["ID"].astype(str)

In [25]:
# unique Method ---df["col"] .unique()
df["Dept"].unique()

<ArrowStringArray>
['IT', 'Sales', 'HR', 'Operations']
Length: 4, dtype: str

In [26]:
df.iloc[0 , 1] ="Rohit"

In [27]:
df

    ID     Name  Age        Dept  Salary
0  101    Rohit   27          IT   72000
1  102    mohit   29       Sales   43000
2  103     yash   37          HR   32000
3  104   keshav   34          IT   55000
4  105    karan   39       Sales   49000
5  106    rahul   24  Operations   79000
6  107    aryan   26          IT  124000
7  108    arjun   31       Sales   91000
8  109   aditya   28          HR   67000
9  110  chandan   33  Operations   70000

In [28]:
df.loc[9 , "Dept"] = "POERATIONS"

In [29]:
df

    ID     Name  Age        Dept  Salary
0  101    Rohit   27          IT   72000
1  102    mohit   29       Sales   43000
2  103     yash   37          HR   32000
3  104   keshav   34          IT   55000
4  105    karan   39       Sales   49000
5  106    rahul   24  Operations   79000
6  107    aryan   26          IT  124000
7  108    arjun   31       Sales   91000
8  109   aditya   28          HR   67000
9  110  chandan   33  POERATIONS   70000

In [30]:
df["Dept"].unique()

<ArrowStringArray>
['IT', 'Sales', 'HR', 'Operations', 'POERATIONS']
Length: 5, dtype: str

In [31]:
# Valie_Counts Method ----- df[col].Value_Counts
df["Dept"].value_counts()

Dept
IT            3
Sales         3
HR            2
Operations    1
POERATIONS    1
Name: count, dtype: int64

In [32]:
# Replace method
df["Dept"].replace("OPERATIONS","Support",)

0            IT
1         Sales
2            HR
3            IT
4         Sales
5    Operations
6            IT
7         Sales
8            HR
9    POERATIONS
Name: Dept, dtype: str

In [33]:
df["Dept"].replace({"support" : "Operation" , "IT" : "Tech" , "SALES" : "Sales"})

0          Tech
1         Sales
2            HR
3          Tech
4         Sales
5    Operations
6          Tech
7         Sales
8            HR
9    POERATIONS
Name: Dept, dtype: str

In [34]:
df

    ID     Name  Age        Dept  Salary
0  101    Rohit   27          IT   72000
1  102    mohit   29       Sales   43000
2  103     yash   37          HR   32000
3  104   keshav   34          IT   55000
4  105    karan   39       Sales   49000
5  106    rahul   24  Operations   79000
6  107    aryan   26          IT  124000
7  108    arjun   31       Sales   91000
8  109   aditya   28          HR   67000
9  110  chandan   33  POERATIONS   70000

In [35]:
# new  Columns
df["city"] = ["Delhi" , "Mumbai"]

ValueError: Length of values (2) does not match length of index (10)

In [38]:
df

    ID     Name  Age        Dept  Salary
0  101    Rohit   27          IT   72000
1  102    mohit   29       Sales   43000
2  103     yash   37          HR   32000
3  104   keshav   34          IT   55000
4  105    karan   39       Sales   49000
5  106    rahul   24  Operations   79000
6  107    aryan   26          IT  124000
7  108    arjun   31       Sales   91000
8  109   aditya   28          HR   67000
9  110  chandan   33  POERATIONS   70000

In [39]:
# Renam Columns
df.column = ["Id" , "Full Name" , "Age" , "Dept" , "Salary" , "City"]

In [40]:
df

    ID     Name  Age        Dept  Salary
0  101    Rohit   27          IT   72000
1  102    mohit   29       Sales   43000
2  103     yash   37          HR   32000
3  104   keshav   34          IT   55000
4  105    karan   39       Sales   49000
5  106    rahul   24  Operations   79000
6  107    aryan   26          IT  124000
7  108    arjun   31       Sales   91000
8  109   aditya   28          HR   67000
9  110  chandan   33  POERATIONS   70000

In [41]:
l = []
for i in df.colimns:
    if i == "Full Name":
        l.append("Name")
    else:
        l

AttributeError: 'DataFrame' object has no attribute 'colimns'

In [42]:
df = df[["Id" , "Name" , "City" , "Age" , "Dept" , "Salary"]]

KeyError: "['Id', 'City'] not in index"

In [ ]:
df

In [62]:
df["Country"] = ["india" , for i in range(10)]
df["Company"] = ["ABC Pvt. Ltd." for i in range(10)]

SyntaxError: did you forget parentheses around the comprehension target? (3717516993.py, line 1)

In [63]:
df.drop(Columns = ["Country" , "Company"] , Inplace = True)

TypeError: DataFrame.drop() got an unexpected keyword argument 'Columns'. Did you mean 'columns'?

In [64]:
df

    ID     Name  Age        Dept  Salary
0  101    Rohit   27          IT   72000
1  102    mohit   29       Sales   43000
2  103     yash   37          HR   32000
3  104   keshav   34          IT   55000
4  105    karan   39       Sales   49000
5  106    rahul   24  Operations   79000
6  107    aryan   26          IT  124000
7  108    arjun   31       Sales   91000
8  109   aditya   28          HR   67000
9  110  chandan   33  POERATIONS   70000

# Class third

In [110]:
import pandas as pd

In [111]:
df = pd.DataFrame({
    "ID":[101,102,103,104,105,106,107,108,109,110],
    "Name":["Rohan","mohit","yash","keshav","karan","rahul","aryan","arjun","aditya","chandan"],
    "Age":[27,29,37,34,39,24,26,31,28,33,],
    "Dept":["IT","Sales","HR","IT","Sales","Operations","IT","Sales","HR","Operations"],
    "Salary":[72000,43000,32000,55000,49000,79000,124000,91000,67000,70000]
})

In [112]:
pd.DataFrame(di)

    ID     Name  Age        Dept  Salary
0  101    Rohan   27          IT   72000
1  102    mohit   29       Sales   43000
2  103     yash   37          HR   32000
3  104   keshav   34          IT   55000
4  105    karan   39       Sales   49000
5  106    rahul   24  Operations   79000
6  107    aryan   26          IT  124000
7  108    arjun   31       Sales   91000
8  109   aditya   28          HR   67000
9  110  chandan   33  Operations   70000

In [113]:
l = []
for i in df.columns:
    l.append(i.title())

In [114]:
print(l)

['Id', 'Name', 'Age', 'Dept', 'Salary']

In [115]:
df.columns = l

In [116]:
df

    Id     Name  Age        Dept  Salary
0  101    Rohan   27          IT   72000
1  102    mohit   29       Sales   43000
2  103     yash   37          HR   32000
3  104   keshav   34          IT   55000
4  105    karan   39       Sales   49000
5  106    rahul   24  Operations   79000
6  107    aryan   26          IT  124000
7  108    arjun   31       Sales   91000
8  109   aditya   28          HR   67000
9  110  chandan   33  Operations   70000

In [117]:
emp_id , emp_name , emp_age , emp_dept , emp_salary , emp_city

NameError: name 'emp_id' is not defined

In [104]:
l =[]
for i in df.columns:
    l.append("emp_"+ i.lower())

In [107]:
print(l)

['emp_id', 'emp_name', 'emp_age', 'emp_dept', 'emp_salary']

In [108]:
df.columns = 1

TypeError: Index(...) must be called with a collection of some kind, 1 was passed

In [109]:
df

    Id     Name  Age        Dept  Salary
0  101    Rohan   27          IT   72000
1  102    mohit   29       Sales   43000
2  103     yash   37          HR   32000
3  104   keshav   34          IT   55000
4  105    karan   39       Sales   49000
5  106    rahul   24  Operations   79000
6  107    aryan   26          IT  124000
7  108    arjun   31       Sales   91000
8  109   aditya   28          HR   67000
9  110  chandan   33  Operations   70000

In [75]:
l = []
for i in df["end_name"]:
    l.append(i.tital())

KeyError: 'end_name'

In [76]:
print(l)

[]

In [77]:
df["emp_name"] = l

ValueError: Length of values (0) does not match length of index (10)

In [78]:
df

    Id     Name  Age        Dept  Salary
0  101    Rohan   27          IT   72000
1  102    mohit   29       Sales   43000
2  103     yash   37          HR   32000
3  104   keshav   34          IT   55000
4  105    karan   39       Sales   49000
5  106    rahul   24  Operations   79000
6  107    aryan   26          IT  124000
7  108    arjun   31       Sales   91000
8  109   aditya   28          HR   67000
9  110  chandan   33  Operations   70000

In [79]:
l = []
for i in df["end_name"]:
    l.append(i.tital())

KeyError: 'end_name'

In [80]:
a = "emp_name"
print(a.repalce("emp_", "").title())

AttributeError: 'str' object has no attribute 'repalce'

In [81]:
print(l)

[]

In [82]:
df.columns = 1

TypeError: Index(...) must be called with a collection of some kind, 1 was passed

In [83]:
df

    Id     Name  Age        Dept  Salary
0  101    Rohan   27          IT   72000
1  102    mohit   29       Sales   43000
2  103     yash   37          HR   32000
3  104   keshav   34          IT   55000
4  105    karan   39       Sales   49000
5  106    rahul   24  Operations   79000
6  107    aryan   26          IT  124000
7  108    arjun   31       Sales   91000
8  109   aditya   28          HR   67000
9  110  chandan   33  Operations   70000

In [84]:
a = "emp_name"
print(a.repalce("emp_","72k").title())

AttributeError: 'str' object has no attribute 'repalce'

In [85]:
print(l)

[]

In [86]:
df.colunmns = 1

In [87]:
df

    Id     Name  Age        Dept  Salary
0  101    Rohan   27          IT   72000
1  102    mohit   29       Sales   43000
2  103     yash   37          HR   32000
3  104   keshav   34          IT   55000
4  105    karan   39       Sales   49000
5  106    rahul   24  Operations   79000
6  107    aryan   26          IT  124000
7  108    arjun   31       Sales   91000
8  109   aditya   28          HR   67000
9  110  chandan   33  Operations   70000

In [88]:
a  = 72000
print(f"{a/1000}k")

72.0k

In [89]:
a = 72000
a = str(a/1000)+"k"
print(a)

72.0k

In [90]:
l = []
for i in df["salary"]:
    l.append(str(i/1000)+"k")
print(l)

KeyError: 'salary'

In [91]:
df["salary"] = l

ValueError: Length of values (0) does not match length of index (10)

In [92]:
df

    Id     Name  Age        Dept  Salary
0  101    Rohan   27          IT   72000
1  102    mohit   29       Sales   43000
2  103     yash   37          HR   32000
3  104   keshav   34          IT   55000
4  105    karan   39       Sales   49000
5  106    rahul   24  Operations   79000
6  107    aryan   26          IT  124000
7  108    arjun   31       Sales   91000
8  109   aditya   28          HR   67000
9  110  chandan   33  Operations   70000

In [93]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Id      10 non-null     int64
 1   Name    10 non-null     str
 2   Age     10 non-null     int64
 3   Dept    10 non-null     str
 4   Salary  10 non-null     int64
dtypes: int64(3), str(2)
memory usage: 630.0 bytes

In [94]:
a = "72.0k"
print(float(a.replace("k" , ""))*1000)

72000.0

In [95]:
l =[]
for i in df["Salary"]:
    l.append(int(float(i.repalce("k", ""))*1000))

AttributeError: 'int' object has no attribute 'repalce'

In [96]:
print(l)

[]

In [97]:
df["Salary"] = l

ValueError: Length of values (0) does not match length of index (10)

In [98]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Id      10 non-null     int64
 1   Name    10 non-null     str
 2   Age     10 non-null     int64
 3   Dept    10 non-null     str
 4   Salary  10 non-null     int64
dtypes: int64(3), str(2)
memory usage: 630.0 bytes

In [99]:
# filter 
df[df["Salary"]> 55000]

    Id     Name  Age        Dept  Salary
0  101    Rohan   27          IT   72000
5  106    rahul   24  Operations   79000
6  107    aryan   26          IT  124000
7  108    arjun   31       Sales   91000
8  109   aditya   28          HR   67000
9  110  chandan   33  Operations   70000

In [100]:
# \ (or) 
df[(df["City"] == "Delhi") | (df["City"] == "Mumbai")]

KeyError: 'City'

In [101]:
# & (and) 
df[(df["City"] == "Delhi") & (df["Dept"] == "IT")]

KeyError: 'City'

In [5]:
import pandas as pd

In [6]:
import numpy as np

In [7]:
di = {
    "ID" : [101,102,103,104,105,106,107,108,109,110,111,112,113,114,115],
    "Name" : ["Rohan" , "Mohit" , "Karan" , "Gaurav" , "Shivam" , "Sahil" , "Kartik" , "Rahul" , "Aryan" , "Aditya" , "Arjun" , "Abhishek" , "Manav" , "Rohit" , "Rishabh"],
    "Age" : [17,19,16,27,np.nan , 24 , np.nan , 19 , np.nan , 25 , 21 , 27 , np.nan , 28 , np.nan],
    "Salary" : [45000 , 84000 ,np.nan , 57000, 60000 , np.nan , 35000 , 74000 , 91000 , np.nan , 55000 , np.nan , 64000 , np.nan , 58000],
    "City"  : ["Delhi" , "Mumbai" , "Pune" , np.nan , "Delhi" , "Kolkata" , "Bangalore" , "Delhi" , np.nan , "Mumbai" , "Delhi" , "Chennai" , "Delhi" , np.nan , "Delhi"],
    "Country" : ["India" , "India" , "India" , "India" , "India" , np.nan , np.nan , "India", np.nan, "India" , "India" , np.nan , "India" , "India" , np.nan]  
}

In [8]:
df = pd.DataFrame(di)

In [9]:
df

     ID      Name   Age   Salary       City Country
0   101     Rohan  17.0  45000.0      Delhi   India
1   102     Mohit  19.0  84000.0     Mumbai   India
2   103     Karan  16.0      NaN       Pune   India
3   104    Gaurav  27.0  57000.0        NaN   India
4   105    Shivam   NaN  60000.0      Delhi   India
5   106     Sahil  24.0      NaN    Kolkata     NaN
6   107    Kartik   NaN  35000.0  Bangalore     NaN
7   108     Rahul  19.0  74000.0      Delhi   India
8   109     Aryan   NaN  91000.0        NaN     NaN
9   110    Aditya  25.0      NaN     Mumbai   India
10  111     Arjun  21.0  55000.0      Delhi   India
11  112  Abhishek  27.0      NaN    Chennai     NaN
12  113     Manav   NaN  64000.0      Delhi   India
13  114     Rohit  28.0      NaN        NaN   India
14  115   Rishabh   NaN  58000.0      Delhi     NaN

In [10]:
df.isnull().sum()

ID         0
Name       0
Age        5
Salary     5
City       3
Country    5
dtype: int64

In [14]:
# fillna ----> df[col].fillna(value)
df["Country"].fillna("india", inplace = True)

C:\Users\HP\AppData\Local\Temp\ipykernel_1548\4006256839.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Country"].fillna("india", inplace = True)

0     India
1     India
2     India
3     India
4     India
5     india
6     india
7     India
8     india
9     India
10    India
11    india
12    India
13    India
14    india
Name: Country, dtype: str

In [12]:
df

     ID      Name   Age   Salary       City Country
0   101     Rohan  17.0  45000.0      Delhi   India
1   102     Mohit  19.0  84000.0     Mumbai   India
2   103     Karan  16.0      NaN       Pune   India
3   104    Gaurav  27.0  57000.0        NaN   India
4   105    Shivam   NaN  60000.0      Delhi   India
5   106     Sahil  24.0      NaN    Kolkata     NaN
6   107    Kartik   NaN  35000.0  Bangalore     NaN
7   108     Rahul  19.0  74000.0      Delhi   India
8   109     Aryan   NaN  91000.0        NaN     NaN
9   110    Aditya  25.0      NaN     Mumbai   India
10  111     Arjun  21.0  55000.0      Delhi   India
11  112  Abhishek  27.0      NaN    Chennai     NaN
12  113     Manav   NaN  64000.0      Delhi   India
13  114     Rohit  28.0      NaN        NaN   India
14  115   Rishabh   NaN  58000.0      Delhi     NaN

In [13]:
df.isnull().sum()

ID         0
Name       0
Age        5
Salary     5
City       3
Country    5
dtype: int64

In [15]:
df["Age"].fillna(df["Age"].median() , inplace = True)

C:\Users\HP\AppData\Local\Temp\ipykernel_1548\3579205347.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Age"].fillna(df["Age"].median() , inplace = True)

0     17.0
1     19.0
2     16.0
3     27.0
4     22.5
5     24.0
6     22.5
7     19.0
8     22.5
9     25.0
10    21.0
11    27.0
12    22.5
13    28.0
14    22.5
Name: Age, dtype: float64

In [16]:
df

     ID      Name   Age   Salary       City Country
0   101     Rohan  17.0  45000.0      Delhi   India
1   102     Mohit  19.0  84000.0     Mumbai   India
2   103     Karan  16.0      NaN       Pune   India
3   104    Gaurav  27.0  57000.0        NaN   India
4   105    Shivam   NaN  60000.0      Delhi   India
5   106     Sahil  24.0      NaN    Kolkata     NaN
6   107    Kartik   NaN  35000.0  Bangalore     NaN
7   108     Rahul  19.0  74000.0      Delhi   India
8   109     Aryan   NaN  91000.0        NaN     NaN
9   110    Aditya  25.0      NaN     Mumbai   India
10  111     Arjun  21.0  55000.0      Delhi   India
11  112  Abhishek  27.0      NaN    Chennai     NaN
12  113     Manav   NaN  64000.0      Delhi   India
13  114     Rohit  28.0      NaN        NaN   India
14  115   Rishabh   NaN  58000.0      Delhi     NaN

In [17]:
df.isnull().sum()

ID         0
Name       0
Age        5
Salary     5
City       3
Country    5
dtype: int64

In [18]:
df["Salary"].fillna(df["Salary"].mean() , inplace = True)

C:\Users\HP\AppData\Local\Temp\ipykernel_1548\2444132494.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Salary"].fillna(df["Salary"].mean() , inplace = True)

0     45000.0
1     84000.0
2     62300.0
3     57000.0
4     60000.0
5     62300.0
6     35000.0
7     74000.0
8     91000.0
9     62300.0
10    55000.0
11    62300.0
12    64000.0
13    62300.0
14    58000.0
Name: Salary, dtype: float64

In [19]:
df

     ID      Name   Age   Salary       City Country
0   101     Rohan  17.0  45000.0      Delhi   India
1   102     Mohit  19.0  84000.0     Mumbai   India
2   103     Karan  16.0      NaN       Pune   India
3   104    Gaurav  27.0  57000.0        NaN   India
4   105    Shivam   NaN  60000.0      Delhi   India
5   106     Sahil  24.0      NaN    Kolkata     NaN
6   107    Kartik   NaN  35000.0  Bangalore     NaN
7   108     Rahul  19.0  74000.0      Delhi   India
8   109     Aryan   NaN  91000.0        NaN     NaN
9   110    Aditya  25.0      NaN     Mumbai   India
10  111     Arjun  21.0  55000.0      Delhi   India
11  112  Abhishek  27.0      NaN    Chennai     NaN
12  113     Manav   NaN  64000.0      Delhi   India
13  114     Rohit  28.0      NaN        NaN   India
14  115   Rishabh   NaN  58000.0      Delhi     NaN

In [20]:
df.isnull().sum()

ID         0
Name       0
Age        5
Salary     5
City       3
Country    5
dtype: int64

In [21]:
df["City"].mode()

0    Delhi
Name: City, dtype: str

In [24]:
df["City"].fillna("Delhi" , inplace = True)

C:\Users\HP\AppData\Local\Temp\ipykernel_1548\3128818157.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["City"].fillna("Delhi" , inplace = True)

0         Delhi
1        Mumbai
2          Pune
3         Delhi
4         Delhi
5       Kolkata
6     Bangalore
7         Delhi
8         Delhi
9        Mumbai
10        Delhi
11      Chennai
12        Delhi
13        Delhi
14        Delhi
Name: City, dtype: str

In [23]:
df

     ID      Name   Age   Salary       City Country
0   101     Rohan  17.0  45000.0      Delhi   India
1   102     Mohit  19.0  84000.0     Mumbai   India
2   103     Karan  16.0      NaN       Pune   India
3   104    Gaurav  27.0  57000.0        NaN   India
4   105    Shivam   NaN  60000.0      Delhi   India
5   106     Sahil  24.0      NaN    Kolkata     NaN
6   107    Kartik   NaN  35000.0  Bangalore     NaN
7   108     Rahul  19.0  74000.0      Delhi   India
8   109     Aryan   NaN  91000.0        NaN     NaN
9   110    Aditya  25.0      NaN     Mumbai   India
10  111     Arjun  21.0  55000.0      Delhi   India
11  112  Abhishek  27.0      NaN    Chennai     NaN
12  113     Manav   NaN  64000.0      Delhi   India
13  114     Rohit  28.0      NaN        NaN   India
14  115   Rishabh   NaN  58000.0      Delhi     NaN

In [25]:
di = {
    "ID" : [101,102,103,104,105,106,107,108,109,110],
    "Product" : ["Iphone" , "Samsung" , "Vivo" , "Oppo" , "Iphone" , "Vivo" , "Samsung" , "Oppo" , "Iphone" , "Oppo"],
    "Price" : [124000 , 48000 , 24000 , 26000 , np.nan , 32000 , 54000 , np.nan , 11500, np.nan]
}

In [26]:
df = pd.DataFrame(di)
df

    ID  Product     Price
0  101   Iphone  124000.0
1  102  Samsung   48000.0
2  103     Vivo   24000.0
3  104     Oppo   26000.0
4  105   Iphone       NaN
5  106     Vivo   32000.0
6  107  Samsung   54000.0
7  108     Oppo       NaN
8  109   Iphone  115000.0
9  110     Oppo       NaN

In [29]:
ip_mean = df[df["Product"] == "Iphone"]["Price"].mean()
print(ip_mean)

119500.0

In [30]:
op_mean = df[df["Product"] =="Oppo"]["Price"].mean()
print(op_mean)

26000.0

In [31]:
df["Price"].fillna(0 , Inplace = True)

TypeError: NDFrame.fillna() got an unexpected keyword argument 'Inplace'. Did you mean 'inplace'?

In [34]:
l = []
for i , j in zip(df["Product"] , df["Price"]):
    if i == "Iphone" and j == 0:
        l.append(ip_mean)
    if i == "Oppo" and j == 0:
    elif:
        l.append(op_mean)
    elif:
        l.append(j)

IndentationError: expected an indented block after 'if' statement on line 5 (3691486259.py, line 6)

In [33]:
print(l)

NameError: name 'l' is not defined

In [36]:
d1 = {
    "emp_id" : [101 , 102 , 103 , 104 , 105],
    "emp_name" : ["Rohan" , "Mohit" , "Yash" , "Keshave" , "Rahul"],
    "emp_age" :[24,29 ,37 ,28, 31],
    "emp_city" :["Delhi" , "Mumbai" , "pune" , "kolata", "Haryana"]
 }

personal = pd.DataFrame(d1)
Personal

NameError: name 'Personal' is not defined

In [39]:
d2 = {
    "emp_id" : [101 , 102 , 103 , 104 , 105],
    "emp_dept" : ["IT" , "Sales" , "HR" , "IT" , "Operaations"],
    "emp_joining" :["2023-05-17" , "2024-06-19", "2025-07-20" , "2026-08-21" , "2026-10-23"],
    "emp_salary" :[68000 , 420000 ,310000, 50000 , 48000]
}

Personal = pd.DataFrame(d2)
Personal

   emp_id     emp_dept emp_joining  emp_salary
0     101           IT  2023-05-17       68000
1     102        Sales  2024-06-19      420000
2     103           HR  2025-07-20      310000
3     104           IT  2026-08-21       50000
4     105  Operaations  2026-10-23       48000

In [ ]:
# Merage --- pd.Merge(df1 , df2 , on = "Common_column" , how = "type_of_Joine")
pd.merge(Personal , Professional , on = "emp_id" , how = "inner")

In [ ]:
pd.merge(Personal , Professional , on = "emp_id" , how = "right")

In [ ]:
pd.merge(Personal , Professional , on = "emp_id" , how = "Right")

In [ ]:
pd.merge(Personal , Professional , on = "emp_id" , how = "outer")

In [2]:
import pandas as pd

In [ ]:
df = pd.read_excel(r